package Paquete;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Axcell Espinal
 */
public class Info extends javax.swing.JDialog {

    /**
     * Creates new form Info
     */
    public Info(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        dialogoImagen();
    }
    public void dialogoImagen()//metodo para cargar la imagen del fondo del menu principal
    {
        System.out.println("imagen de dialogo activada");
       JLabel marcoImagen = new JLabel(new ImageIcon("src/main/java/Imagenes/PiedraTextura2.jpg"));
       marcoImagen.setBounds(0, 0, 780, 480);
       fondoDialogo.add(marcoImagen);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoDialogo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion del software");
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        fondoDialogo.setBackground(new java.awt.Color(153, 255, 153));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        infoText.setEditable(false);
        infoText.setText("Proyecto final de programacion I desarrollado por:\n\nAxcell Alberto Espinal Nuñez 2019-8358\nPamela Villar Muñoz 2019-8458\nAndrews Luis Fernández calderón 2019-7565\nSamuel Baez 2019-8085");
        jScrollPane2.setViewportView(infoText);

        javax.swing.GroupLayout fondoDialogoLayout = new javax.swing.GroupLayout(fondoDialogo);
        fondoDialogo.setLayout(fondoDialogoLayout);
        fondoDialogoLayout.setHorizontalGroup(
            fondoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoDialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoDialogoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        fondoDialogoLayout.setVerticalGroup(
            fondoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoDialogoLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDialogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoDialogo;
    private javax.swing.JTextPane infoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
