/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import Tablas.Tabla;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Axcell Espinal
 */
public class RegistroReuniones extends javax.swing.JFrame {

    /**
     * Creates new form RegistroReuniones
     */
    public RegistroReuniones() 
    {
        initComponents();
        imagenMenu();
        imagenSubmenu();
    }
     public void imagenMenu()//metodo para cargar la imagen del fondo del menu principal
    {
        System.out.println("imagen menu principal activada");
       JLabel marcoImagen = new JLabel(new ImageIcon("src/main/java/Imagenes/escritorio.jpg"));
       marcoImagen.setBounds(-20, 0, 720, 480);
       FondoMenu.add(marcoImagen);   
    }
     private void infoVentana() {
        Info informacion = new Info(this, true);
        informacion.show();
    }
       private void Tablas() {
        Tabla tablita = new Tabla();
        tablita.show();
    }
              private void Buscador() {
        Buscador b = new Buscador();
        b.show();
    }
          public void imagenSubmenu()//metodo para cargar la imagen que sobre pone elmenu principal
    {
        System.out.println("imagen Sub menu activada");
       JLabel marcoImagen = new JLabel(new ImageIcon("src/main/java/Imagenes/pizzarra.jpg"));
       marcoImagen.setBounds(-195, -120, 720, 480);
       pizzarraMenu.add(marcoImagen);   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoMenu = new javax.swing.JPanel();
        pizzarraMenu = new javax.swing.JPanel();
        nuevaReunion = new javax.swing.JButton();
        listaR = new javax.swing.JButton();
        info = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asistente de reuniones");
        setResizable(false);

        FondoMenu.setBackground(new java.awt.Color(153, 255, 153));

        pizzarraMenu.setBackground(new java.awt.Color(255, 102, 102));

        nuevaReunion.setBackground(new java.awt.Color(153, 255, 255));
        nuevaReunion.setText("Nueva reunion");
        nuevaReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaReunionActionPerformed(evt);
            }
        });

        listaR.setBackground(new java.awt.Color(153, 255, 255));
        listaR.setText("Buscar reunion");
        listaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRActionPerformed(evt);
            }
        });

        info.setBackground(new java.awt.Color(153, 255, 255));
        info.setText("Info del software");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pizzarraMenuLayout = new javax.swing.GroupLayout(pizzarraMenu);
        pizzarraMenu.setLayout(pizzarraMenuLayout);
        pizzarraMenuLayout.setHorizontalGroup(
            pizzarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizzarraMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pizzarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevaReunion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        pizzarraMenuLayout.setVerticalGroup(
            pizzarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizzarraMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(nuevaReunion)
                .addGap(18, 18, 18)
                .addComponent(listaR)
                .addGap(18, 18, 18)
                .addComponent(info)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel1.setText("Version 1.0.0");

        javax.swing.GroupLayout FondoMenuLayout = new javax.swing.GroupLayout(FondoMenu);
        FondoMenu.setLayout(FondoMenuLayout);
        FondoMenuLayout.setHorizontalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(pizzarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        FondoMenuLayout.setVerticalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(pizzarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        infoVentana();
    }//GEN-LAST:event_infoActionPerformed

    private void nuevaReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaReunionActionPerformed
        // TODO add your handling code here:
        Tablas();
    }//GEN-LAST:event_nuevaReunionActionPerformed

    private void listaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRActionPerformed
        // TODO add your handling code here:
        Buscador();
    }//GEN-LAST:event_listaRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroReuniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroReuniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroReuniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroReuniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroReuniones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoMenu;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listaR;
    private javax.swing.JButton nuevaReunion;
    private javax.swing.JPanel pizzarraMenu;
    // End of variables declaration//GEN-END:variables
}
