/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.Jframess;

import BACKEND.Clases.*;
import FRONTEND.Imagenes.Imagen;
import FRONTEND.Jdialogs.Calendario;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axcell Espinal
 */
public class NuevaReunion extends javax.swing.JFrame {

    DefaultTableModel modelo;

    private int guardar = 0;
    Reuniones reunion = new Reuniones();

    Conectar Con = new Conectar();
    Connection cn = Con.conexion("root", "Axcell2015");

    Edicion editor = new Edicion();

    public NuevaReunion() {
        initComponents();

        Imagen F = new Imagen();
        F.getAll("meet.png", 0, -15, 810, 455);
        F.cargarImagen(panelFondo);

        crearTabla();
    }

    private void crearTabla() {
        //este comando impide que se pueda editar la tabla
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //este comando agrega las columnas a la tabla
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora de inicio");
        modelo.addColumn("Hora final");
        modelo.addColumn("Lugar");
        modelo.addColumn("notas/detalles");
        tablaDatos.setModel(modelo);

        String[] datos = new String[7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM eventos");
            while (rs.next()) {

                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);

                modelo.addRow(datos);
            }
            tablaDatos.setModel(modelo);
        } catch (Exception e) {
        }
    }

    private void cargarImagenes() {
        System.out.println("imagen menu activada");
        JLabel imagen = new JLabel(new ImageIcon("src/main/java/FRONTEND/Imagenes/meet.png"));
        imagen.setBounds(-210, -120, 810, 455);
        panelFondo.add(imagen);
    }

    private void cargarDatos() {
        reunion.setNombre(nombreField.getText());
        reunion.setFecha(fechaField.getText());
        reunion.setHoraI(hiField.getText());
        reunion.setHoraF(fhField.getText());
        reunion.setLugar(lugarField.getText());
        reunion.setDetalles(notasField.getText());
    }

    private void limpiarCeldas() {
        id.setText("");
        nombreField.setText("");
        fechaField.setText("");
        hiField.setText("");
        fhField.setText("");
        lugarField.setText("");
        notasField.setText("");       
        guardar = 0;
    }

    private void validarFecha() {
        try {
            Calendario c = new Calendario(this, true);
            c.show();
            fechaField.setText(c.Fecha());
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, "Introduzca datos validos, no sea imbecil");
            validarFecha();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        nombre1 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        horaI1 = new javax.swing.JLabel();
        horaf1 = new javax.swing.JLabel();
        lugar1 = new javax.swing.JLabel();
        notas1 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        fechaField = new javax.swing.JTextField();
        hiField = new javax.swing.JTextField();
        lugarField = new javax.swing.JTextField();
        notasField = new javax.swing.JTextField();
        fhField = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        mGuardar = new javax.swing.JMenuItem();
        mEliminar = new javax.swing.JMenuItem();
        mLimpiar = new javax.swing.JMenuItem();
        mBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva reunion");
        setPreferredSize(new java.awt.Dimension(551, 380));
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(153, 255, 153));
        panelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaDatos.setBackground(new java.awt.Color(153, 204, 255));
        tablaDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        jButton1.setText("Volver");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nombre1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nombre1.setText("Nombre");

        fecha1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fecha1.setText("Fecha");

        horaI1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        horaI1.setText("Hora de inicio");

        horaf1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        horaf1.setText("Hora final");

        lugar1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lugar1.setText("Lugar");

        notas1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        notas1.setText("Notas/detalles");

        nombreField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        fechaField.setEditable(false);
        fechaField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fechaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaFieldMouseClicked(evt);
            }
        });

        id.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hiField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelFondoLayout.createSequentialGroup()
                                            .addComponent(nombre1)
                                            .addGap(47, 47, 47))
                                        .addGroup(panelFondoLayout.createSequentialGroup()
                                            .addComponent(nombreField)
                                            .addGap(15, 15, 15)))
                                    .addComponent(horaI1)
                                    .addComponent(id))
                                .addGap(12, 12, 12)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fecha1)
                                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fhField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horaf1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notas1)
                                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(notasField, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(lugarField))
                                    .addComponent(lugar1))))
                        .addGap(18, 64, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre1)
                    .addComponent(fecha1)
                    .addComponent(lugar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaf1)
                    .addComponent(horaI1)
                    .addComponent(notas1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu.setText("Archivo");

        mGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mGuardar.setText("Guardar");
        mGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarActionPerformed(evt);
            }
        });
        jMenu.add(mGuardar);

        mEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mEliminar.setText("Eliminar");
        mEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEliminarActionPerformed(evt);
            }
        });
        jMenu.add(mEliminar);

        mLimpiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mLimpiar.setText("Limpiar");
        mLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLimpiarActionPerformed(evt);
            }
        });
        jMenu.add(mLimpiar);

        mBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mBuscar.setText("Buscar reunion");
        mBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBuscarActionPerformed(evt);
            }
        });
        jMenu.add(mBuscar);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainMenu mm = new MainMenu();
        this.dispose();
        mm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarActionPerformed
        switch (guardar) {
            case 0:
                cargarDatos();

                editor.guardar(reunion);
                crearTabla();

                limpiarCeldas();
                break;

            case 1:
                reunion.setID(Integer.parseInt(id.getText()));
                cargarDatos();
                
                editor.actualizar(reunion);
                crearTabla();

                limpiarCeldas();
                guardar = 0;
                
                break;

            default:
                cargarDatos();

                editor.guardar(reunion);
                crearTabla();

                limpiarCeldas();
                break;
        }
    }//GEN-LAST:event_mGuardarActionPerformed

    private void mBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBuscarActionPerformed
        Buscador b = new Buscador();
        b.show();
        this.dispose();
    }//GEN-LAST:event_mBuscarActionPerformed

    private void mEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEliminarActionPerformed
        reunion.setID(Integer.parseInt(id.getText()));

        editor.eliminar(reunion);

        limpiarCeldas();
        crearTabla();
    }//GEN-LAST:event_mEliminarActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        int fila = tablaDatos.getSelectedRow();
        if (fila >= 0) {
            id.setText(tablaDatos.getValueAt(fila, 0).toString());
            nombreField.setText(tablaDatos.getValueAt(fila, 1).toString());
            fechaField.setText(tablaDatos.getValueAt(fila, 2).toString());
            hiField.setText(tablaDatos.getValueAt(fila, 3).toString());
            fhField.setText(tablaDatos.getValueAt(fila, 4).toString());
            lugarField.setText(tablaDatos.getValueAt(fila, 5).toString());
            notasField.setText(tablaDatos.getValueAt(fila, 6).toString());
        } else {
            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }
        
        guardar = 1;
    }//GEN-LAST:event_tablaDatosMouseClicked

    private void mLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLimpiarActionPerformed
        limpiarCeldas();
    }//GEN-LAST:event_mLimpiarActionPerformed

    private void fechaFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaFieldMouseClicked
        validarFecha();
    }//GEN-LAST:event_fechaFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha1;
    private javax.swing.JTextField fechaField;
    private javax.swing.JTextField fhField;
    private javax.swing.JTextField hiField;
    private javax.swing.JLabel horaI1;
    private javax.swing.JLabel horaf1;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lugar1;
    private javax.swing.JTextField lugarField;
    private javax.swing.JMenuItem mBuscar;
    private javax.swing.JMenuItem mEliminar;
    private javax.swing.JMenuItem mGuardar;
    private javax.swing.JMenuItem mLimpiar;
    private javax.swing.JLabel nombre1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel notas1;
    private javax.swing.JTextField notasField;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
